### ISSUE TITLE
`WrongMethodTypeException` with blackbird

### ISSUE THREAD

**Issue by naveg** [FasterXML/jackson-modules-base#142] opened 2021-06-27 00:23 UTC
After upgrading to Java 16 and Jackson 2.12 with Blackbird replacing Afterburner, we are seeing WrongMethodTypeException occur frequently. The strange thing is that this affects only 25-40% of requests. An identical request made repeatedly will fail at that rate.

Example stack trace:

```
java.lang.invoke.WrongMethodTypeException: expected ()ToIntFunction but found ()ToIntFunction
	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:506)
	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:515)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.createProperty(BBSerializerModifier.java:116)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.lambda$findProperties$0(BBSerializerModifier.java:64)
	at com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$runnable$0(Unchecked.java:31)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.findProperties(BBSerializerModifier.java:65)
	at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.changeProperties(BBSerializerModifier.java:49)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:407)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:290)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:235)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:169)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1421)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:753)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:311)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:115)
	... 74 common frames omitted
```

This is occuring in a Dropwizard application.

Happy to provide more information as needed, and will continue to dig and update this issue with what I find.

**Comment by cowtowncoder** [comment] 2021-07-09 01:03
cc @stevenschlansker

**Comment by stevenschlansker** [comment] 2021-07-09 16:14
This is a strange exception message. `ToIntFunction` is part of `java.base` so there should never be more than one...
Do you have a reproducible test case you can share? What does the definition of the type you serialize look like?

**Comment by stevenschlansker** [comment] 2021-07-13 19:47
@Naveg , a couple more questions: do you use any custom or non-default classloaders, or set the thread context class loader ever?

**Comment by cowtowncoder** [comment] 2022-11-02 21:42
Cannot reproduce, no more info added, closing. May be reopened/refiled with necessary info.

**Closed by cowtowncoder** 2022-11-02 21:42 UTC
Labels: blackbird

**Comment by Noitcereon** [comment] 2026-06-17 10:59
I just wanted to note that I have encountered a similar exception and provide what info I can. The exception started to occur after we upgraded from Java 17 -> Java 21. I am unsure how to reproduce it. We do not see the exception all the time, but the exception somehow seems to be cached. Restarting the Spring Boot (v3.5.4) application makes it work again temporarily. StackTrace shows `ToBooleanFunction` instead of `ToIntFunction`, but is otherwise very similar.

The application uses jackson-bom 2.19.2.

StackTrace from the application I work on:
```log
org.springframework.core.codec.EncodingException: JSON encoding error: handle's method type ()ToBooleanFunction but found ()ToBooleanFunction\n\tat 
org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:260)\n\tat 
org.springframework.http.codec.json.AbstractJackson2Encoder.lambda$encode$0(AbstractJackson2Encoder.java:159)\n\tat 
(redacted a bunch of reactor.core lines for brevity)
truncated\nCaused by: com.fasterxml.jackson.databind.JsonMappingException: handle's method type ()ToBooleanFunction but found ()ToBooleanFunction (through reference chain: custom.model.Stigningsbegraensning[\"initielMsb\"]->custom.model.InitielMsb[\"grundskyldsberegningGlLovgivning\"])\n\tat 
com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:400)\n\tat 
com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:359)\n\tat 
com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:324)\n\tat 
com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:765)\n\tat 
com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)\n\tat 
custom.serialization.CoreModule$ModifyingSerializer.serialize(CoreModule.java:75)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.ObjectPropertyWriter.serializeAsField(ObjectPropertyWriter.java:97)\n\tat 
com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)\n\tat com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)\n\tat 
custom.services.serialization.CoreModule$ModifyingSerializer.serialize(CoreModule.java:75)\n\tat 
com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:503)\n\tat 
com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:342)\n\tat 
com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1587)\n\tat 
com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)\n\tat 
org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:253)\n\t... 362 common 
frames omitted\nCaused by: java.lang.invoke.WrongMethodTypeException: handle's method type ()ToBooleanFunction but found 
()ToBooleanFunction\n\tat java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:522)\n\tat 
java.lang.invoke.Invokers.checkExactType(Invokers.java:531)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.createProperty(BBSerializerModifier.java:142)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.lambda$findProperties$0(BBSerializerModifier.java:69)\n\tat 
com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$runnable$0(Unchecked.java:31)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.findProperties(BBSerializerModifier.java:70)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.changeProperties(BBSerializerModifier.java:54)\n\tat 
com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:418)\n\tat 
com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:292)\n\tat 
com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:237)\n\tat 
com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:171)\n\tat 
com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1554)\n\tat 
com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1502)\n\tat 
com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:752)\n\tat 
com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:64)\n\tat 
com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:906)\n\tat 
com.fasterxml.jackson.module.blackbird.ser.ObjectPropertyWriter.serializeAsField(ObjectPropertyWriter.java:77)\n\tat 
com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)\n\t... 373 common frames 
omitted\n"} 
```

The stacktrace mentions `InitielMsb#grundskyldsberegningGlLovgivning`, which is an object containing 4 fields, one of which is a primitive boolean (compared to Boolean wrapper class). Maybe this difference between primitive boolean and wrapper class could be the issue? (pure speculation)

I have also found a similar looking issue in https://github.com/ben-manes/caffeine/issues/1111 , where the conclusion seems to have been to use `MethodHandle#invoke` instead of `MethodHandle#invokeExact`.

I hope this helps anyone that reads this.

**Comment by stevenschlansker** [comment] 2026-06-17 16:24
Thank you @Noitcereon for bringing this up again - if there is some kind of latent JVM bug here we'd love to help collaborate to at least get a sensible report filed.
Can you provide additional information on your setup, like exactly which JVM versions have reproduced this issue, as well as whether you use any custom classloaders or anything else "funky" we should be aware of?

**Comment by stevenschlansker** [comment] 2026-06-17 16:55
Also @Noitcereon what GC configuration do you use? maybe share all your JVM launch arguments?

**Comment by Noitcereon** [comment] 2026-06-18 12:37
Thanks for paying attention to it! 😄 
As far as I'm aware there are not any custom classloaders or anything like that in use.

Regarding JVM, here is what is used:
**JVM:** java-21-openjdk-21.0.10.0.7-1 (Red Hat)
**JVM launch args**: /usr/bin/java -XX:HeapDumpPath=/redacted -Xmx6g -Xms32m -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -jar application.jar

**Comment by Noitcereon** [comment] 2026-06-19 08:42
Another exception that seems related, but is deserialization:
```log
"java.lang.invoke.WrongMethodTypeException: handle's method type (MethodHandle)Function but found 
MethodHandle)Function\n\tat 
java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:522)\n\tat 
java.lang.invoke.Invokers.checkExactType(Invokers.java:531)\n\tat 
com.fasterxml.jackson.module.blackbird.deser.CreatorOptimizer.lambda$createOptimized$0(CreatorOptimizer.java:73)\n\tat 
com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$supplier$1(Unchecked.java:41)\n\tat 
com.fasterxml.jackson.module.blackbird.deser.CreatorOptimizer.createOptimized(CreatorOptimizer.java:80)\n\tat 
com.fasterxml.jackson.module.blackbird.deser.BBDeserializerModifier.updateBuilder(BBDeserializerModifier.java:102)\n\tat 
com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:288)\n\tat 
com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:152)\n\tat 
com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:472)\n\tat 
com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:416)\n\tat 
com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:318)\n\tat 
com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:285)\n\tat 
com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:175)\n\tat 
com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)\n\tat 
com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5102)\n\tat 
com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4972)\n\tat 
com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3948)\n\tat 
```

**Comment by cowtowncoder** [comment] 2026-06-19 14:40
@Noitcereon Just a quick question on this:

    The application uses jackson-bom 2.19.2.

I know there hasn't been too many changes, but 2.19.x is no longer supported -- can this be reproduced with either 2.22.0 (latest version) or 2.21.4 (latest LTS patch)?

I'll label this as `2.x`; not sure if it occurs on 3.x either.

**Comment by stevenschlansker** [comment] 2026-06-19 17:19
I assume we are all talking about x86_64 here (no aarch64?) - and, are you able to reproduce the situation on demand? I set Claude on trying to create a reproduction case, but not much luck so far. Claude wants to go ahead and file a JDK bug, but I would really like to see a reproducer first, unless we really cannot get there.

Claude suggests seeing if you can reproduce under `-Xint` (this is probably not safe to run in production?)
Another thought: if you can reproduce the problem, we could try to instrument your run (whether through a Java agent or patched JDK) to get additional information...

This starts to get tricky fast. Open to suggestions as to which directions might be productive to explore, or when we should give up and file a bug with the JDK...

```
  We spent a while trying to reproduce this. We couldn't trigger it, but we decoded what the exception means and
  ruled out several hypotheses — sharing the findings, since we think this is a JVM bug worth reporting upstream.

  What the message means. invokeExact (Invokers.checkExactType) compares the handle's MethodType to the call site's
  expected MethodType by reference identity (!=), not .equals(). That's only safe because MethodType.methodType(...)
  interns every instance through a process-wide weak table, so equal types should be the same object.
  "()ToBooleanFunction but found ()ToBooleanFunction" — identical on both sides — means two instances exist that are
  .equals() but not ==: the interning invariant has been violated. Same root cause as ben-manes/caffeine#1111, and
  it's why their invokeExact→invoke workaround hides it (invoke routes through .equals()).

  It can't originate in the Java intern logic. We read the intern implementations on JDK 17 (ConcurrentWeakInternSet)
  and 21 (ReferencedKeyMap) in full: on both, a race-loser clears its weak ref without enqueueing, and stale-entry
  removal can only match a dead entry, never a live equal one. So a live duplicate of a reachable type can't come
  from a pure-Java race — it must arise below the Java layer: GC weak-reference processing transiently
  clearing/returning-stale a reachable intern entry, or a C2 miscompile of the @ForceInline identity check.

  What we tried — none reproduced it:
  
  - Synthetic harnesses asserting the intern invariant and hammering invokeExact, across both architectures (aarch64,
  x86_64), all four collectors (G1, ZGC, generational ZGC, Shenandoah), JDK 17 and 21, product and fastdebug.
  - fastdebug VMs with GC verification (+VerifyBeforeGC/AfterGC, +ShenandoahVerify, +ZVerify*) — these turn a
  transient inconsistency into a hard abort — plus C2 stress (+StressLCM/GCM/IGVN, +DeoptimizeALot) with an -Xint
  control.
  - First-time call-site linkage via fresh classloaders, and launch storms of thousands of short JVMs (the field rate
  is ~10 in thousands of launches, clustered at warmup).
  - Real libraries on the exact builds: Caffeine 3.1.7 build() + Blackbird 2.12.7 on Corretto 17.0.8.7.1 (~10.8B
  builds), and — driven by @Noitcereon's details (Red Hat 21.0.10.0.7-1, Shenandoah, -Xms32m -Xmx6g) — on that exact
  build under Shenandoah, covering both failing sites: serialization (BBSerializerModifier) and deserialization
  (CreatorOptimizer). That run did 1.32B Caffeine builds + 1.80B serializes + 1.33B deserializes; repeated under
  fastdebug 21.0.11 + ShenandoahVerify. All held, no VM aborts.
  
  Tens of billions of operations, the exact field build and collector, both sites, heavy thread oversubscription to
  widen race windows — zero reproductions.

  On the version question (@cowtowncoder): we think this is a JVM bug, not a Jackson one — the duplicate MethodType
  arises in the VM, and Jackson is just what calls invokeExact and observes it (Caffeine hit the identical thing with
  no Jackson involved). A newer Jackson is unlikely to fix it, though switching invokeExact→invoke would mask it. We
  checked the 21.0.10→21.0.11 diff for the 17→21 onset @Noitcereon reports and found nothing relevant to this path
  (JDK-8358751 mentions compiled lambda forms but is a different bug — a hard SIGSEGV crash, not this exception).

  Next step. We have a self-contained harness and a write-up, and plan to file with OpenJDK as an "is this known, and
  how would you instrument it?" report — we can't hand them a one-command reproduction, so we'll be upfront about
  that. @Noitcereon, two things would help: does it still happen on 2.21.4 / 2.22.0 (as @cowtowncoder asked)? And
  does running with -Xint make it disappear? The -Xint answer would tell us whether it's the JIT or GC.
```

**Comment by stevenschlansker** [comment] 2026-06-19 18:41
ok @Noitcereon I asked Claude, "what can we give the OP to do further diagnostics with" and it came up with this Java agent that you could try.

The intent is that the agent "should" be safe to run in production with minimal / no impact. Of course, this is all vibe-coded, with no warranty ;) but if we do end up finding a bug in the JDK, eternal glory will be ours!

Here's the agent Claude came up with:

https://github.com/stevenschlansker/jackson-modules-base/tree/claude/jdk-methodtype-invokeexact-repro/jdk-mt-repro/op-diagnostic

If you're feeling brave and can reasonably reliably reproduce the problem, the output of this program might help make a better JDK bug to submit.

**Comment by Noitcereon** [comment] 2026-06-22 07:29
Answering a few questions here:

> 1. Are you able to reproduce the situation on demand?

As mentioned previously, no, I am unable to reproduce it on demand. Aside: At this point the "solution" has been to disable Blackbird module.

> 2. I assume we are all talking about x86_64 here?

It is indeed x86_64.

> 3. Can this be reproduced with either 2.21.4 or 2.22.0?

I am unsure, but I would assume so, since there are seemingly no relevant changes to Blackbird. Since I cannot reproduce the error on demand I cannot really answer the question easily.

> 4. Can you gather more diagnostic data (e.g. via `-Xint` or the vibe-coded agent)?

The bug appears sporadically, so I do not know when, or if, I can gather more info, but I will try.

**Comment by ben-manes** [comment] 2026-06-22 07:39
fwiw:
In Caffeine the usage of invokeExact() was to instantiate a factory, which was cached for reuse. That meant it was called only a few times per JVM to load the optimized classes for the cache configuration. Since the benchmarks show it’s only 7% faster than an invoke() call, it seemed reasonable to accept the user feedback without a reproduction. I attempted to across many jvm runs with hostile jit settings but couldn’t trigger the error.

At a glance your usage appears similar so you might end up making a similar conclusion.

**Comment by stevenschlansker** [comment] 2026-06-22 15:40
In this particular case, the invokeExact is appealing, because we go through this path on every field read or write (not just once at configuration time).

All that said, I think the actual performance benefit nowadays of Blackbird is highly marginal in most use cases, and invoke vs invokeExact isn't likely to perturb any benchmarks focused outside of just property setting.

Then again, it sucks to work around what feels like a broken JDK :) and would be cool to fix this eventually... but as you say I already spent a fair bit of time trying to reproduce with no luck as well.

If this keeps happening, and we don't figure a proper fix, I think we can either advise affected users to not use Blackbird, or swap for `invoke` if that's too many users.

**Comment by Noitcereon** [comment] 2026-08-25 11:43
Just a heads up: I have given up on gathering more diagnostics.  I can, however, confirm that I have not experienced the issue since disabling blackbird.
