### ISSUE TITLE
Paranamer exception

### ISSUE THREAD

**Issue by bojanv55** [FasterXML/jackson-modules-base#24] opened 2017-03-03 09:06 UTC
In case that I have empty class that extends base one e.g.:

```
public class Child extends Parent {
public Child(int version){ super(version); }
}

public abstract class Parent implements CommandMessage {
public final int version;
public Parent(int version){ this.version=version;}
}

public interface CommandMessage extends Message {
}

public interface Message {
}
```

and if I try to use paranamer for Child class, I get an exception - no default constructor; As soon as I add one new field to Child class, paranamer works OK.

**Comment by cowtowncoder** [comment] 2017-03-06 18:22
First of all, it would be helpful to indicate version of Jackson you are using; and ideally test with at least latest patch version of minor version (that is, if you were using 2.8.1, try out 2.8.7).

In your case I think you will need to use `@JsonCreator` to indicate constructor to use: this should be done anyway, but there is some auto-detection logic that may work in some cases -- like more than one parameter, where constructor parameter names are available (using Paranamer or Java 8 parameter names module). Single-parameter name is complicated by the fact that there are two different styles of constructors: "delegating" (in which the argument is mapped exactly as-is to argument type) and "property-based" (in which argument is taken as name/value pair to map, so input must be JSON Object).

**Comment by bojanv55** [comment] 2017-03-27 15:12
OK. I was using class with single parameter in constructor and been using paranamer (expected to work out of the box). After adding mix-ins with @JsonCreator it works OK.

**Comment by cowtowncoder** [comment] 2017-03-27 19:24
@bojanv55 Paranamer does give access to constructor names, but existence of name does not in itself tell much about if user intended a constructor to be used as Creator. And specifically in case of 1-argument constructor there is also ambiguity between "as-properties" (to match incoming Object) or "delegate" (to match value of any type, as-is -- in which case name is not needed or used).

With Jackson 3 we may revisit logic to see if there could be set of heuristics to use, but this is genuinely complicated thing and there is backwards compatibility to consider (that is: we should not change logic to use constructor that was not meant to be used -- in many cases manual construction uses different constructor than deserializer).

Anyway. I think in your case it was just down to not auto-detecting single argument case due to ambiguity, so closing as this is expected behavior at this point. Possible future enhancements (which would go in `jackson-databind`, also apply to Java 8 with parameter names) notwithstanding.

**Closed by cowtowncoder** 2017-03-27 19:24 UTC
