### ISSUE TITLE
Jackson's @XmlElementRefs implementation doesn't produce expected XML

### ISSUE THREAD

**Issue by oliverkuntze** [FasterXML/jackson-modules-base#92] opened 2019-12-13 12:18 UTC
Hey,
either Jackson does not implement JAXB's @XmlElementRefs annotation or the implementation is not producing the corresponding XML.

Given the following no XML element `Type1` or `Type2` gets created. 
Furthermore if setting XmlAccessType.FIELD a XML element `nachrichtentyp` gets created.
Using only one @XmlElementRef without the surrounding @XmlElementRefs the XML is created correctly. Putting one @XmlElementRef into a surrounding @XmlElementRefs the XML is not created correctly. 
So in my opinion it has to be the @XmlElementRefs implementation that has a flaw.
Using the Glassfish RI everything works just fine. 

```java
@XmlAccessorType(XmlAccessType.NONE)
@Builder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Nachricht {
    @XmlElementRefs({
            @XmlElementRef(name = "Type1", type = Type1.class),
            @XmlElementRef(name = "Type2", type = Type2.class)
    })
    private Nachrichtentyp nachrichtentyp;
}
```

where

```java
@XmlTransient
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public abstract class Nachrichtentyp {
    @XmlElement(name = "Service", required = true)
    protected Service service;
}
```

and

```java
@XmlRootElement(name = "Type1")
@XmlAccessorType(XmlAccessType.NONE)
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Type1 extends Nachrichtentyp {
    @XmlElement(name = "Something")
    private String something;
}
```

and

```java
@XmlRootElement(name = "Type2")
@XmlAccessorType(XmlAccessType.NONE)
@SuperBuilder
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class Type2 extends Nachrichtentyp {
}
```

Cheers
Oliver

**Comment by cowtowncoder** [comment] 2020-11-14 04:26
Duplicate of https://github.com/FasterXML/jackson-dataformat-xml/issues/379, closing.

Comments from that issue apply; new issues to file should go in that repo, if any (since while this module translates annotations it is XML module that actually applies them to input/output).

**Closed by cowtowncoder** 2020-11-14 04:26 UTC
Labels: jaxb
