### ISSUE TITLE
Problem deserializing a class with ancestors

### ISSUE THREAD

**Issue by danjee** [FasterXML/jackson-modules-base#203] opened 2023-04-05 13:48 UTC
Issue deserializing a spring data PageImpl.
I've excluded the legacy afterburner from my dependencies and a deserializer started failing.
My custom class is extending PageImpl which extends Chunk.

```java
@JsonIgnoreProperties(ignoreUnknown = true, value = {"pageable"})
public class RestPage<T> extends PageImpl<T> {

    private static final long serialVersionUID = 851236798223548446L;

    @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
    public RestPage(
            @JsonProperty("content") final List<T> content,
            @JsonProperty("page") final int page,
            @JsonProperty("size") final int size,
            @JsonProperty("totalElements") final long total) {
        super(content, PageRequest.of(page, size), total);
    }

    public RestPage(final Page<T> page) {
        super(page.getContent(), page.getPageable(), page.getTotalElements());
    }
}
```
The error I get is: java.lang.IllegalAccessException: class is not public: org.springframework.data.domain.Chunk.getContent

I'm using latest version 2.14.2 under java17

**Comment by cowtowncoder** [comment] 2023-04-27 23:34
We would need a reproduction to see what is happening: description along isn't sufficient.

I am not 100% clear for example if failure is with or without Afterburner (I assume with since it's filed here... ?).

I would suggest trying 2.15.0 that was just released, just in case.

**Comment by cowtowncoder** [comment] 2023-10-23 23:59
Cannot reproduce, closing. May be re-opened/re-filed with test case.

**Closed by cowtowncoder** 2023-10-23 23:59 UTC
Labels: afterburner, need-test-case
